image: docker:19.03.1

services:
  - docker:19.03.1-dind

before_script:
  - docker info # SHOW THE DOCKER INFO FIRST
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - test # WILL BE ADDED SOMETIME
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  VERSION: '7.16.1' # FIREBASE-TOOLS VERSION
  DOCKER_TLS_CERTDIR: '/certs'

# BUILD THE DOCKER CONTAINER WITH TAGS AND THE ARGUMENTS
build_container:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$VERSION:lts-rc
  script:
    - docker build . -f ./node-lts/Dockerfile && \
      --no-cache --pull -t $IMAGE_TAG
      --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      --build-arg CI_JOB_ID=$CI_JOB_ID
      --build-arg CI_PIPELINE_ID=$CI_PIPELINE_ID
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg VERSION=$VERSION
  after_script:
    - docker push $IMAGE_TAG
  except:
    - master
  only:
    changes:
      - node-lts/Dockerfile

build_container:buster:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$VERSION:lts-buster-rc
  script:
    - docker build . -f ./node-lts/buster/Dockerfile && \
      --no-cache --pull -t $IMAGE_TAG
      --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      --build-arg CI_JOB_ID=$CI_JOB_ID
      --build-arg CI_PIPELINE_ID=$CI_PIPELINE_ID
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg VERSION=$VERSION
  after_script:
    - docker push $IMAGE_TAG
  except:
    - master
  only:
    changes:
      - node-lts/buster/Dockerfile

build_container:alpine:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$VERSION:lts-alpine-rc
  script:
    - docker build . --no-cache --pull -t $IMAGE_TAG
      --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      --build-arg CI_JOB_ID=$CI_JOB_ID
      --build-arg CI_PIPELINE_ID=$CI_PIPELINE_ID
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg VERSION=$VERSION
  after_script:
    - docker push $IMAGE_TAG
  except:
    - master
  only:
    changes:
      - Dockerfile

# BUILD THE DOCKER CONTAINER WITH TAGS AND THE ARGUMENTS
build_container:master:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$VERSION
  script:
    - docker build . --no-cache --pull
      -t $IMAGE_TAG
      -t $IMAGE_TAG-alpine
      -t $IMAGE_TAG:latest
      --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      --build-arg CI_JOB_ID=$CI_JOB_ID
      --build-arg CI_PIPELINE_ID=$CI_PIPELINE_ID
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg VERSION=$VERSION

  after_script:
    - docker push $IMAGE_TAG-alpine
    - docker push $IMAGE_TAG
    - docker push $IMAGE_TAG:latest
  only:
    - master
