# *-----------------------------------------[ TEMPLATE FOR DEPLOY BUILD JOB ]
deploy:template: &deploy_template
  stage: deploy
  # variables:
  # `DEV_IMAGE_TAG` IS THE TAG USED IN THE BUILD STAGE. NOTICE THE -dev-
  # DEV_IMAGE_TAG: $CI_REGISTRY_IMAGE:$SUFFIX_TAG-dev-$VERSION
  # DOCKER_HUB_IMAGE_TAG: $DOCKER_HUB_ORG/$CI_PROJECT_NAME:$SUFFIX_TAG-$VERSION
  before_script:
    # GET THE VERSION OF FIREBASE TOOLS FROM FILE
    - VERSION=`cat FIREBASE_TOOLS_VERSION`
    - echo FIREBASE_TOOLS_VERSION $VERSION
    # - DEV_IMAGE_TAG=$CI_REGISTRY_IMAGE:$SUFFIX_TAG-dev-$VERSION
    # - DOCKER_HUB_IMAGE_TAG=$DOCKER_HUB_ORG/$CI_PROJECT_NAME:$SUFFIX_TAG-$VERSION
    - echo DEV_IMAGE_TAG $DEV_IMAGE_TAG
    - echo DOCKER_HUB_IMAGE_TAG $DOCKER_HUB_IMAGE_TAG
  script:
    - docker pull $DEV_IMAGE_TAG
    # after_script:
    - echo Pulled $DEV_IMAGE_TAG
    # TODO: PUT THIS IN A DEPLOY STAGE
    # - docker push $IMAGE_TAG # PUSHES TO GITLAB REGISTRY
    # RE-TAG FOR DOCKER HUB.
    - docker tag $DEV_IMAGE_TAG $DOCKER_HUB_IMAGE_TAG
    - docker tag $DEV_IMAGE_TAG $DOCKER_HUB_IMAGE_TAG-latest
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    # THEN PUSH BOTH
    - docker push $DOCKER_HUB_IMAGE_TAG
    - docker push $$DOCKER_HUB_IMAGE_TAG-latest
  rules:
    # IF COMMIT TAG IS (RELEASE / or -) (v) MAJOR.MINOR.PATCH https://regexr.com/51ap2
    - if: $CI_COMMIT_TAG =~ /^(?:(release)(\/|-)|)+(v|)(0|[1-9]\d*).(0|[1-9]\d*)\.(0|[1-9]\d*)$/
      when: manual

# *---------------------------------------------------------------[ node lts ]
deploy:lts:buster:
  variables:
    SUFFIX_TAG: lts-buster
    FILE_NAME: ./node-lts/latest-lts/buster.Dockerfile
    DEV_IMAGE_TAG: $CI_REGISTRY_IMAGE:$SUFFIX_TAG-dev-$VERSION
    DOCKER_HUB_IMAGE_TAG: $DOCKER_HUB_ORG/$CI_PROJECT_NAME:$SUFFIX_TAG-$VERSION
  <<: *deploy_template # THE BUILD TEMPLATE

deploy:lts:
  variables:
    # IMAGE_TAG: $CI_REGISTRY_IMAGE:lts-$VERSION
    SUFFIX_TAG: lts
    FILE_NAME: ./node-lts/latest-lts/Dockerfile
    DEV_IMAGE_TAG: $CI_REGISTRY_IMAGE:$SUFFIX_TAG-dev-$VERSION
    DOCKER_HUB_IMAGE_TAG: $DOCKER_HUB_ORG/$CI_PROJECT_NAME:$SUFFIX_TAG-$VERSION
  <<: *deploy_template

# *---------------------------------------------------------------[ node 12 ]
deploy:12:buster:
  variables:
    # IMAGE_TAG: $CI_REGISTRY_IMAGE:12-buster-$VERSION
    SUFFIX_TAG: 12-buster
    FILE_NAME: ./node-lts/12/buster.Dockerfile
    DEV_IMAGE_TAG: $CI_REGISTRY_IMAGE:$SUFFIX_TAG-dev-$VERSION
    DOCKER_HUB_IMAGE_TAG: $DOCKER_HUB_ORG/$CI_PROJECT_NAME:$SUFFIX_TAG-$VERSION
  <<: *deploy_template # THE BUILD TEMPLATE

deploy:12:
  variables:
    # IMAGE_TAG: $CI_REGISTRY_IMAGE:12-$VERSION
    SUFFIX_TAG: 12
    FILE_NAME: ./node-lts/12/Dockerfile
    DEV_IMAGE_TAG: $CI_REGISTRY_IMAGE:$SUFFIX_TAG-dev-$VERSION
    DOCKER_HUB_IMAGE_TAG: $DOCKER_HUB_ORG/$CI_PROJECT_NAME:$SUFFIX_TAG-$VERSION
  <<: *deploy_template # THE BUILD TEMPLATE

# *---------------------------------------------------------------[ node 10 ]
deploy:10:buster:
  variables:
    # IMAGE_TAG: $CI_REGISTRY_IMAGE:10-buster-$VERSION
    SUFFIX_TAG: 10-buster
    FILE_NAME: ./node-lts/10/buster.Dockerfile
    DEV_IMAGE_TAG: $CI_REGISTRY_IMAGE:$SUFFIX_TAG-dev-$VERSION
    DOCKER_HUB_IMAGE_TAG: $DOCKER_HUB_ORG/$CI_PROJECT_NAME:$SUFFIX_TAG-$VERSION
  <<: *deploy_template # THE BUILD TEMPLATE

deploy:10:
  variables:
    # IMAGE_TAG: $CI_REGISTRY_IMAGE:10-$VERSION
    SUFFIX_TAG: 10
    FILE_NAME: ./node-lts/10/Dockerfile
    DEV_IMAGE_TAG: $CI_REGISTRY_IMAGE:$SUFFIX_TAG-dev-$VERSION
    DOCKER_HUB_IMAGE_TAG: $DOCKER_HUB_ORG/$CI_PROJECT_NAME:$SUFFIX_TAG-$VERSION
  <<: *deploy_template # THE BUILD TEMPLATE

# *---------------------------------------------------------------[ node 8 ]
deploy:8:buster:
  variables:
    # IMAGE_TAG: $CI_REGISTRY_IMAGE:8-buster-$FIREBASE_TOOLS_VERSION_NODE_8
    SUFFIX_TAG: 8-buster
    FILE_NAME: ./node-lts/8/buster.Dockerfile
    VERSION: $FIREBASE_TOOLS_VERSION_NODE_8
    DEV_IMAGE_TAG: $CI_REGISTRY_IMAGE:$SUFFIX_TAG-dev-$VERSION
    DOCKER_HUB_IMAGE_TAG: $DOCKER_HUB_ORG/$CI_PROJECT_NAME:$SUFFIX_TAG-$VERSION
  <<: *deploy_template # THE BUILD TEMPLATE
  before_script:
    # GET THE VERSION OF FIREBASE TOOLS FROM FILE
    - VERSION=`cat FIREBASE_TOOLS_VERSION_NODE_8`
    - echo FIREBASE_TOOLS_VERSION $VERSION
    - echo BUILDING $IMAGE_TAG

deploy:8:
  variables:
    # IMAGE_TAG: $CI_REGISTRY_IMAGE:8-$FIREBASE_TOOLS_VERSION_NODE_8
    SUFFIX_TAG: 8
    FILE_NAME: ./node-lts/8/Dockerfile
    VERSION: $FIREBASE_TOOLS_VERSION_NODE_8
    DEV_IMAGE_TAG: $CI_REGISTRY_IMAGE:$SUFFIX_TAG-dev-$VERSION
    DOCKER_HUB_IMAGE_TAG: $DOCKER_HUB_ORG/$CI_PROJECT_NAME:$SUFFIX_TAG-$VERSION
  <<: *deploy_template # THE BUILD TEMPLATE
  before_script:
    # GET THE VERSION OF FIREBASE TOOLS FROM FILE
    - VERSION=`cat FIREBASE_TOOLS_VERSION_NODE_8`
    - echo FIREBASE_TOOLS_VERSION $VERSION
    - echo BUILDING $IMAGE_TAG

# *----------------------------------------------------[ node lts + alpine ]
deploy:lts:alpine:
  stage: deploy
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:lts-alpine-dev-$VERSION
    SUFFIX_TAG: lts-alpine
  before_script:
    # GET THE VERSION OF FIREBASE TOOLS FROM FILE
    - VERSION=`cat FIREBASE_TOOLS_VERSION`
    - echo FIREBASE_TOOLS_VERSION $VERSION
  script:
    - docker pull $IMAGE_TAG
    # after_script:
    - echo Built $IMAGE_TAG
    # TODO: PUT THIS IN A DEPLOY STAGE
    - docker push $IMAGE_TAG # PUSHES TO GITLAB REGISTRY
    # RE-TAG FOR DOCKER HUB.
    - DOCKER_HUB_IMAGE_TAG=$DOCKER_HUB_ORG/$CI_PROJECT_NAME:$SUFFIX_TAG-$VERSION
    - docker tag $IMAGE_TAG $DOCKER_HUB_IMAGE_TAG
    - docker tag $IMAGE_TAG $DOCKER_HUB_IMAGE_TAG-latest
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - docker push $DOCKER_HUB_IMAGE_TAG
    - docker push $$DOCKER_HUB_IMAGE_TAG-latest
  rules:
    # IF COMMIT TAG IS (RELEASE / or -) (v) MAJOR.MINOR.PATCH https://regexr.com/51ap2
    - if: $CI_COMMIT_TAG =~ /^(?:(release)(\/|-)|)+(v|)(0|[1-9]\d*).(0|[1-9]\d*)\.(0|[1-9]\d*)$/
      when: manual
#! ---------------------------------------------------------------------[ END ]-
